### ISSUE TITLE
[BUG] Investigate inconsistency between scheduler and database

### ISSUE THREAD

**Issue by yatharthranjan** [RADAR-base/RADAR-Appserver#238]
Please check if the bug has already been reported in the Issues Tab and mention any related issues here.

**Describe the bug**
Very rarely the scheduler tries to execute a job with a notification id that does not exist in the database. Ideally, this should not happen, since when a notification is deleted from the database it should also be deleted from the scheduler. 

Relevant Logs-

```
2021-06-18 11:04:00,065 INFO  [quartzScheduler_Worker-2] org.quartz.core.JobRunShell: Job DEFAULT.message-jobdetail-c885ffcf-0bc6-4b20-9b35-919a0908113b-64839 threw a JobExecutionException: 
org.quartz.JobExecutionException: org.radarbase.appserver.exception.InvalidNotificationDetailsException: The Notification with Id 64839 does not exist in project DynaMOBS for user c885ffcf-0bc6-4b20-9b35-919a0908113b
	at org.radarbase.appserver.service.scheduler.quartz.MessageJob.execute(MessageJob.java:103)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.radarbase.appserver.exception.InvalidNotificationDetailsException: The Notification with Id 64839 does not exist in project DynaMOBS for user c885ffcf-0bc6-4b20-9b35-919a0908113b
	at org.radarbase.appserver.service.FcmNotificationService.getNotificationByProjectIdAndSubjectIdAndNotificationId(FcmNotificationService.java:431)
	at org.radarbase.appserver.service.FcmNotificationService$$FastClassBySpringCGLIB$$8d21085e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at org.radarbase.appserver.service.FcmNotificationService$$EnhancerBySpringCGLIB$$8766759a.getNotificationByProjectIdAndSubjectIdAndNotificationId(<generated>)
	at org.radarbase.appserver.service.scheduler.quartz.MessageJob.execute(MessageJob.java:89)
	... 2 common frames omitted
2021-06-18 11:04:00,069 WARN  [quartzScheduler_Worker-2] org.radarbase.appserver.event.listener.QuartzMessageJobListener: The notification does not exist in database and yet was scheduled.

```

**Priority**
3

**Difficulty**
4

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Mobile App**
The Mobile app ,if any, used with this app server
- Name [e.g. RADAR-Questionnaire]
- Version [e.g. 0.5.8]
- Github repo [If applicable]

**Additional context**

**Comment by yatharthranjan** [comment]
should be fixed by #239
